use_frameworks!

platform :ios, '9.0'

target 'FeedVideo_Example' do
  pod 'FeedVideo', :path => '../'

  target 'FeedVideo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
